---
title: "Untitled"
author: "David Cavallucci"
date: "23 June 2015"
output: html_document
---
```{r}


new <- new %>% group_by(id_patients) %>% 
  mutate(ctime = ifelse(index<max(index),rtime,cens_time),
         numlap = sum(lap),
         cens_month = round(cens_time/365.25*12, digits = 1),
         gaptime = rtime-time)
new$numlap <- car::Recode(new$numlap, '2:4=2')
new$index <- car::recode(new$index, '2:4=2')
new$posmarg <- new$posmarg
new %>% mutate(mhlos = hlos - mean(hlos, na.rm=T)) -> new
```

#Weighted stats
```{r, results='hide', warning=FALSE, error=FALSE, message=FALSE, echo=FALSE}

new %>%
  group_by(lap) %>%
  summarise(
    bloodloss = median(bloodloss, na.rm=T),
    hlos = median(hlos, na.rm=T),
    optime = median(optime, na.rm=T),
    margin = median(margin, na.rm=T)
  )

wilcox.test(bloodloss ~ lap, new, conf.int =T)
wilcox.test(hlos ~ lap, new, conf.int =T)
wilcox.test(optime ~ lap, new, conf.int =T)
wilcox.test(margin ~ lap, new, conf.int =T)

#Posmarg - this is actually testing for negative margin but ok..
prop.test(xtabs(~new$lap + new$posmarg))

```






#KM survival and follow-up
```{r, results='hide', warning=FALSE, error=FALSE, message=FALSE, echo=FALSE}
#Median follow-up time by KMPF (reverse kaplan meier)
survfit(Surv(cens_month, cens==0)~1, new)

#KM survival by operative approach (in days)- any dataframe is ok
survfit(Surv(cens_month, cens)~lap+cluster(id_patients), data=new)

#5yr OS by group
summary(survfit(Surv(time,ctime, cens)~lap, new), times=1826.25)

#Logrank - rho=1 gives generalised wilcoxon test, using single dataframe only - 
lros <- svylogrank(Surv(cens_month, cens)~lap, design=design.sing, rho=1)


#RFS strata by index - gaptime is what we want to know - recurrence after each operation
rfskm <- survfit(Surv(gaptime, (rec==1|cens==1))~lap + strata(index) +cluster(id_patients), weights = stable.w, finaldata[finaldata$.imp==1,])

#logrank
svylogrank(Surv(gaptime, (rec==1|cens==1))~lap+strata(index), design=design.sing, rho=1)

#compare only the first or only the second procedures - unweighted, but the numbers are the same
survdiff(Surv(gaptime, (rec==1|cens==1))~lap, finaldata[finaldata$.imp==1,], subset=index==1)
survdiff(Surv(gaptime, (rec==1|cens==1))~lap, finaldata[finaldata$.imp==1,], subset=index==2)

```

#KM output
```{r, results='asis', warning=FALSE, error=FALSE, message=FALSE, echo=FALSE}
#Median FU
pander::pandoc.table(summary(medfup)$table[5:7], caption = "Median follow-up")
#OS
pander::pandoc.table(summary(kmos, scale=365.25/12)$table, caption = "Kaplan-Meier OS")
kable(data.frame("Approach"=c("Open", "Laparoscopic"), summary(fiveyros, times=1826.25)[c(1,9,11,12)]), digits = 2, caption = "5yr OS")
pander::pandoc.table(lros[[2]], caption="Generalised Wilcoxon test, OS")
#RFS
pander::pandoc.table(summary(rfskm, scale=365.25/12)$table, caption = "Kaplan-Meier RFS")
kable(data.frame("Approach"=c("Open", "Laparoscopic"), summary(rfskm, times=1826.25)[c(9,11,12)]), digits = 2, caption = "5yr RFS")

```

#Weighted regression
```{r, results='hide', warning=FALSE, error=FALSE, message=FALSE, echo=FALSE}

#OS
doublerobust.full <- with(imp.mids, coxph(Surv(time,ctime,cens)~lap+cluster(id_patients)+ismajor+isbilateral+primaryN+lesioncount, weights = stable.w))

summary(pool(doublerobust.full))

doublerobust.final <- with(imp.mids, coxph(Surv(time,ctime,cens)~lap+cluster(id_patients), weights = stable.w))

summary(pool(doublerobust.final))

#Compare HR for lap

#PDFS - PWP-CT model
rec_double.full <- with(imp.mids, coxph(Surv(time,rtime,(rec==1|cens==1))~lap+ismajor+isbilateral+primaryN+lesioncount + strata(index), weights = stable.w))

summary(pool(rec_double.full))

rec_double.final <- with(imp.mids, coxph(Surv(gaptime,(rec==1|cens==1))~lap + strata(index), weights = stable.w))

summary(pool(rec_double.final))


#OS_multivariate
doublerobust.mvr  <- with(imp.mids, coxph(Surv(time,ctime,cens)~lap+cluster(id_patients)+ismajor+isbilateral+primaryN+lesioncount+primaryT+bloodloss+mhlos+optime+posmarg, weights = stable.w))

summary(pool(doublerobust.mvr))

########Final multivariate models

os_final <- with(imp.mids, coxph(Surv(time,ctime,cens)~cluster(id_patients)+mhlos+primaryT+lap, weights = stable.w))

summary(pool(os_final))

rec_doublerobust.mvr <- with(imp.mids, coxph(Surv(gaptime,(rec==1|cens==1))~lap+cluster(id_patients)+ismajor+isbilateral+primaryN+lesioncount+primaryT+bloodloss+mhlos+optime+strata(index), weights = stable.w))

#summary(pool(rec_doublerobust.mvr))

rfs_final <- with(imp.mids, coxph(Surv(gaptime, (rec==1|cens==1))~cluster(id_patients)+mhlos+primaryT+isbilateral+lap, weights = stable.w))

#summary(pool(rfs_final))

os.final.data <- as.data.frame(summary(pool(os_final)))
os.final.data <- os.final.data %>% select(est, `Pr(>|t|)`, `lo 95`, `hi 95`)
os.final.data %>% mutate(est=exp(est), `lo 95`=exp(`lo 95`), `hi 95` = exp(`hi 95`)) -> os.final.data
row.names(os.final.data) <- c("hlos", "T2", "T3", "lap")


rfs.final.data <- as.data.frame(summary(pool(rfs_final)))
rfs.final.data <- rfs.final.data %>% select(est, `Pr(>|t|)`, `lo 95`, `hi 95`)
rfs.final.data %>% mutate(est=exp(est), `lo 95`=exp(`lo 95`), `hi 95` = exp(`hi 95`)) -> rfs.final.data
row.names(rfs.final.data) <- c("hlos", "T2", "T3", "isbilateral", "lap")

```

#Regression output
```{r, results='asis', warning=FALSE, error=FALSE, message=FALSE, echo=FALSE}
kable(os.final.data, align = 'l')
kable(rfs.final.data, align = 'l')
source("new_os_surv_curv.R")
source("new_rfs_surv_curv.R")
os_curve
rfs_curve
```